name: "UAT Workflow"
on:
  push:
    branches:
      - dev

jobs:
  Lint-and-migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install packages and lint
        run: npm install
      - name: Lint
        run: npm run format && npm run prettier
